import { BiomeConfig, CarData, CharacterData, GameSaveData, StageMilestoneInfo } from '../types';

export const CHARACTERS: CharacterData[] = [
  {
    id: 'maman_bozorg',
    nameFa: 'مامان بزرگ',
    nameEn: 'Maman Bozorg',
    avatarColor: '#ec4899',
    role: 'راننده مهربان و محتاط',
    description: 'کاراکتر رایگان و آغازین. سرعت استاندارد، کنترل راحت و دست‌فرمان نرم.',
    unlockedByDefault: true,
    price: 0,
    perks: {
      speedMultiplier: 1.0,
      coinMultiplier: 1.0,
      handlingMultiplier: 1.0,
      extraLives: 0,
      hasDrift: false,
      hasRgbLights: false,
    },
  },
  {
    id: 'khaleh_zahra',
    nameFa: 'خاله زهرا',
    nameEn: 'Khaleh Zahra',
    avatarColor: '#f59e0b',
    role: 'برکت‌دار و سکه‌جمع‌کن',
    description: 'سرعت حداکثر کمی آرام‌تر (-۱۰٪)، اما ضریب دریافت سکه‌ها دو برابر (۲x) است!',
    unlockedByDefault: false,
    price: 250,
    perks: {
      speedMultiplier: 0.9,
      coinMultiplier: 2.0,
      handlingMultiplier: 1.05,
      extraLives: 0,
      hasDrift: false,
      hasRgbLights: false,
    },
  },
  {
    id: 'khaleh_maryam',
    nameFa: 'خاله مریم',
    nameEn: 'Khaleh Maryam',
    avatarColor: '#10b981',
    role: 'فرمان‌داری تیز و دقیق',
    description: 'دست‌فرمان فوق‌العاده تیز و دقیق (+۳۰٪ چسبندگی و مانور سریع بین خطوط اتوبان).',
    unlockedByDefault: false,
    price: 500,
    perks: {
      speedMultiplier: 1.05,
      coinMultiplier: 1.1,
      handlingMultiplier: 1.35,
      extraLives: 0,
      hasDrift: false,
      hasRgbLights: false,
    },
  },
  {
    id: 'amir_mahdi',
    nameFa: 'امیر مهدی',
    nameEn: 'Amir Mahdi',
    avatarColor: '#3b82f6',
    role: 'سلاطین لایی‌کشی و دریفت',
    description: 'سرعت بالا (+۱۵٪) و امکان دریفت‌زدن در پیچ‌ها و تغییر خط‌های تند با خط ترمز جذاب.',
    unlockedByDefault: false,
    price: 1000,
    perks: {
      speedMultiplier: 1.18,
      coinMultiplier: 1.25,
      handlingMultiplier: 1.15,
      extraLives: 0,
      hasDrift: true,
      hasRgbLights: false,
    },
  },
  {
    id: 'zandayi',
    nameFa: 'زندایی',
    nameEn: 'Zandayi',
    avatarColor: '#a855f7',
    role: 'نورپردازی رنگین‌کمانی RGB',
    description: 'ضریب سکه نصف (۰.۵x) می‌شود، اما چراغ‌های جلو و زیر ماشین افکت نئونی RGB متحرک دارند!',
    unlockedByDefault: false,
    price: 1800,
    perks: {
      speedMultiplier: 1.1,
      coinMultiplier: 0.5,
      handlingMultiplier: 1.1,
      extraLives: 1,
      hasDrift: false,
      hasRgbLights: true,
    },
  },
  {
    id: 'ali',
    nameFa: 'علی',
    nameEn: 'Ali',
    avatarColor: '#ef4444',
    role: 'سلطان اتوبان و قهرمان',
    description: 'گران‌ترین و قوی‌ترین کاراکتر (مرحله ۵۰+ یا ۵۰۰۰ سکه). دارای ۳ جان اضافی و ضریب سکه ۱.۵x!',
    unlockedByDefault: false,
    price: 5000,
    minLevelToUnlock: 50,
    perks: {
      speedMultiplier: 1.25,
      coinMultiplier: 1.5,
      handlingMultiplier: 1.25,
      extraLives: 3,
      hasDrift: true,
      hasRgbLights: true,
    },
  },
];

export const CARS: CarData[] = [
  {
    id: 1,
    nameFa: 'پیکان جوانان ۴۸',
    nameEn: 'Paykan Javanan 48',
    price: 0,
    bodyColor: '#e11d48',
    secondaryColor: '#ffffff',
    topSpeed: 140,
    acceleration: 60,
    handling: 65,
    armor: 50,
    type: 'classic',
    unlockedByDefault: true,
  },
  {
    id: 2,
    nameFa: 'پراید ۱۱۱ اسپرت',
    nameEn: 'Pride 111 Sport',
    price: 0,
    bodyColor: '#f3f4f6',
    secondaryColor: '#1f2937',
    topSpeed: 145,
    acceleration: 68,
    handling: 75,
    armor: 40,
    type: 'hatchback',
    unlockedByDefault: true,
  },
  {
    id: 3,
    nameFa: 'سمند LX سورن',
    nameEn: 'Samand LX',
    price: 150,
    bodyColor: '#3b82f6',
    secondaryColor: '#1d4ed8',
    topSpeed: 160,
    acceleration: 70,
    handling: 70,
    armor: 65,
    type: 'sedan',
    unlockedByDefault: false,
  },
  {
    id: 4,
    nameFa: 'پژو ۲۰۶ تیپ ۵',
    nameEn: 'Peugeot 206',
    price: 300,
    bodyColor: '#eab308',
    secondaryColor: '#000000',
    topSpeed: 168,
    acceleration: 78,
    handling: 82,
    armor: 55,
    type: 'hatchback',
    unlockedByDefault: false,
  },
  {
    id: 5,
    nameFa: 'پژو پارس ELX گرگ',
    nameEn: 'Pars ELX Wolf',
    price: 450,
    bodyColor: '#ffffff',
    secondaryColor: '#1e293b',
    topSpeed: 175,
    acceleration: 80,
    handling: 78,
    armor: 60,
    type: 'sedan',
    unlockedByDefault: false,
  },
  {
    id: 6,
    nameFa: 'نیسان آبی سالار',
    nameEn: 'Nissan Blue Pickup',
    price: 600,
    bodyColor: '#0284c7',
    secondaryColor: '#22c55e',
    topSpeed: 150,
    acceleration: 65,
    handling: 60,
    armor: 95,
    type: 'pickup',
    unlockedByDefault: false,
  },
  {
    id: 7,
    nameFa: 'تاکسی زرد تهران',
    nameEn: 'Tehran Yellow Taxi',
    price: 750,
    bodyColor: '#eab308',
    secondaryColor: '#1e293b',
    topSpeed: 165,
    acceleration: 75,
    handling: 80,
    armor: 60,
    type: 'taxi',
    unlockedByDefault: false,
  },
  {
    id: 8,
    nameFa: 'پلیس نامحسوس ۱۱۰',
    nameEn: 'Police Patrol 110',
    price: 950,
    bodyColor: '#0f172a',
    secondaryColor: '#ffffff',
    topSpeed: 185,
    acceleration: 85,
    handling: 85,
    armor: 75,
    type: 'police',
    unlockedByDefault: false,
  },
  {
    id: 9,
    nameFa: 'دنا پلاس توربو اتومات',
    nameEn: 'Dena Plus Turbo',
    price: 1200,
    bodyColor: '#475569',
    secondaryColor: '#dc2626',
    topSpeed: 182,
    acceleration: 84,
    handling: 80,
    armor: 70,
    type: 'sedan',
    unlockedByDefault: false,
  },
  {
    id: 10,
    nameFa: 'فولکس بیتل قورباغه‌ای',
    nameEn: 'Retro Beetle',
    price: 1500,
    bodyColor: '#f97316',
    secondaryColor: '#fef08a',
    topSpeed: 160,
    acceleration: 72,
    handling: 88,
    armor: 55,
    type: 'classic',
    unlockedByDefault: false,
  },
  {
    id: 11,
    nameFa: 'شورولت کامارو عضلانی',
    nameEn: 'Muscle Charger',
    price: 1800,
    bodyColor: '#000000',
    secondaryColor: '#facc15',
    topSpeed: 190,
    acceleration: 88,
    handling: 74,
    armor: 80,
    type: 'muscle',
    unlockedByDefault: false,
  },
  {
    id: 12,
    nameFa: 'تویوتا پرادو آفرود',
    nameEn: 'Prado 4x4 Offroad',
    price: 2200,
    bodyColor: '#15803d',
    secondaryColor: '#334155',
    topSpeed: 175,
    acceleration: 75,
    handling: 72,
    armor: 95,
    type: 'suv',
    unlockedByDefault: false,
  },
  {
    id: 13,
    nameFa: 'هیوندای جنسیس کوپه',
    nameEn: 'Genesis Coupe',
    price: 2600,
    bodyColor: '#9333ea',
    secondaryColor: '#f43f5e',
    topSpeed: 195,
    acceleration: 90,
    handling: 86,
    armor: 65,
    type: 'sports',
    unlockedByDefault: false,
  },
  {
    id: 14,
    nameFa: 'مرسدس بنز S500 شاهانه',
    nameEn: 'Mercedes Luxury VIP',
    price: 3000,
    bodyColor: '#1e293b',
    secondaryColor: '#94a3b8',
    topSpeed: 200,
    acceleration: 92,
    handling: 85,
    armor: 85,
    type: 'sedan',
    unlockedByDefault: false,
  },
  {
    id: 15,
    nameFa: 'پورشه ۹۱۱ توربو S',
    nameEn: 'Porsche 911 Turbo',
    price: 3500,
    bodyColor: '#e11d48',
    secondaryColor: '#0f172a',
    topSpeed: 210,
    acceleration: 95,
    handling: 92,
    armor: 70,
    type: 'sports',
    unlockedByDefault: false,
  },
  {
    id: 16,
    nameFa: 'لامبورگینی اونتادور خشمگین',
    nameEn: 'Aventador V12',
    price: 4200,
    bodyColor: '#06b6d4',
    secondaryColor: '#0891b2',
    topSpeed: 220,
    acceleration: 98,
    handling: 90,
    armor: 65,
    type: 'sports',
    unlockedByDefault: false,
  },
  {
    id: 17,
    nameFa: 'سایبر رودستر ۲۰۷۷',
    nameEn: 'Cyber Roadster 2077',
    price: 5000,
    bodyColor: '#0f172a',
    secondaryColor: '#22d3ee',
    topSpeed: 225,
    acceleration: 99,
    handling: 94,
    armor: 80,
    type: 'hyper',
    unlockedByDefault: false,
  },
  {
    id: 18,
    nameFa: 'فرمول یک ردبول توربو',
    nameEn: 'Formula One Redline',
    price: 6000,
    bodyColor: '#1e1b4b',
    secondaryColor: '#fbbf24',
    topSpeed: 235,
    acceleration: 100,
    handling: 98,
    armor: 50,
    type: 'hyper',
    unlockedByDefault: false,
  },
  {
    id: 19,
    nameFa: 'بوگاتی شیرون صاعقه',
    nameEn: 'Chiron Lightning',
    price: 7500,
    bodyColor: '#172554',
    secondaryColor: '#60a5fa',
    topSpeed: 245,
    acceleration: 100,
    handling: 95,
    armor: 85,
    type: 'hyper',
    unlockedByDefault: false,
  },
  {
    id: 20,
    nameFa: 'سلطان طلایی یونس آباد (ویژه)',
    nameEn: 'Younes Gold Sultan',
    price: 10000,
    bodyColor: '#eab308',
    secondaryColor: '#fef08a',
    topSpeed: 250,
    acceleration: 100,
    handling: 100,
    armor: 100,
    type: 'hyper',
    unlockedByDefault: false,
  },
];

export const BIOMES: BiomeConfig[] = [
  {
    id: 'forest',
    nameFa: 'جنگل‌های سرسبز شمال',
    nameEn: 'Green Forest Highway',
    stageRange: [1, 10],
    roadColor: '#2b2d42',
    laneColor: '#edf2f4',
    shoulderColor: '#1e3a1e',
    curbColor1: '#ffffff',
    curbColor2: '#ef4444',
    grassColor: '#15803d',
    nightMode: false,
    weatherEffect: 'none',
    ambientLight: 1.0,
    npcTypes: ['paykan', 'pride', 'sedan'],
  },
  {
    id: 'desert',
    nameFa: 'کویر و تپه‌های شنی لوت',
    nameEn: 'Desert Sand Dunes',
    stageRange: [11, 20],
    roadColor: '#3f3730',
    laneColor: '#fef08a',
    shoulderColor: '#a16207',
    curbColor1: '#ffffff',
    curbColor2: '#f59e0b',
    grassColor: '#ca8a04',
    nightMode: false,
    weatherEffect: 'none',
    ambientLight: 1.0,
    npcTypes: ['truck', 'tractor', 'nissan_blue', 'semi'],
  },
  {
    id: 'rain',
    nameFa: 'اتوبان بارانی و آسفالت خیس',
    nameEn: 'Rainy Night Highway',
    stageRange: [21, 30],
    roadColor: '#111827',
    laneColor: '#93c5fd',
    shoulderColor: '#0f172a',
    curbColor1: '#60a5fa',
    curbColor2: '#1e40af',
    grassColor: '#064e3b',
    nightMode: true,
    weatherEffect: 'rain',
    ambientLight: 0.35,
    npcTypes: ['sedan', 'tanker', 'ambulance', 'truck'],
  },
  {
    id: 'snow',
    nameFa: 'جاده برفی و یخ‌زده البرز',
    nameEn: 'Snowy Alpine Pass',
    stageRange: [31, 40],
    roadColor: '#334155',
    laneColor: '#e2e8f0',
    shoulderColor: '#94a3b8',
    curbColor1: '#f8fafc',
    curbColor2: '#38bdf8',
    grassColor: '#f1f5f9',
    nightMode: false,
    weatherEffect: 'snow',
    ambientLight: 0.9,
    npcTypes: ['snowplow', 'truck', 'sedan', 'semi'],
  },
  {
    id: 'noir',
    nameFa: 'خیابان‌های نوآر سیاه و سفید',
    nameEn: 'Monochrome Noir City',
    stageRange: [41, 50],
    roadColor: '#18181b',
    laneColor: '#e4e4e7',
    shoulderColor: '#27272a',
    curbColor1: '#ffffff',
    curbColor2: '#52525b',
    grassColor: '#3f3f46',
    nightMode: true,
    weatherEffect: 'none',
    ambientLight: 0.4,
    npcTypes: ['limo', 'sedan', 'truck', 'paykan'],
  },
  {
    id: 'lava',
    nameFa: 'جاده آتشفشانی دماوند خروشان',
    nameEn: 'Volcanic Magma Gorge',
    stageRange: [51, 60],
    roadColor: '#1c1917',
    laneColor: '#f97316',
    shoulderColor: '#7c2d12',
    curbColor1: '#ea580c',
    curbColor2: '#451a03',
    grassColor: '#b91c1c',
    nightMode: true,
    weatherEffect: 'embers',
    ambientLight: 0.45,
    npcTypes: ['firetruck', 'truck', 'sports', 'semi'],
  },
  {
    id: 'mountain',
    nameFa: 'گردنه کوهستانی و صخره‌ای حیران',
    nameEn: 'Rocky Mountain Ridge',
    stageRange: [61, 70],
    roadColor: '#334155',
    laneColor: '#fbbf24',
    shoulderColor: '#475569',
    curbColor1: '#e2e8f0',
    curbColor2: '#dc2626',
    grassColor: '#475569',
    nightMode: false,
    weatherEffect: 'none',
    ambientLight: 0.95,
    npcTypes: ['bus', 'nissan_blue', 'truck', 'sedan'],
  },
  {
    id: 'ocean',
    nameFa: 'اتوبان ساحلی خلیج فارس',
    nameEn: 'Ocean Coastal Highway',
    stageRange: [71, 80],
    roadColor: '#1e293b',
    laneColor: '#fef08a',
    shoulderColor: '#0284c7',
    curbColor1: '#38bdf8',
    curbColor2: '#ffffff',
    grassColor: '#0369a1',
    nightMode: false,
    weatherEffect: 'none',
    ambientLight: 1.0,
    npcTypes: ['sedan', 'sports', 'bus', 'semi'],
  },
  {
    id: 'cyberpunk',
    nameFa: 'شهر نئونی سایبرپانک ۲۰۷۷',
    nameEn: 'Cyberpunk Neon City',
    stageRange: [81, 90],
    roadColor: '#090d16',
    laneColor: '#06b6d4',
    shoulderColor: '#1e1b4b',
    curbColor1: '#f43f5e',
    curbColor2: '#06b6d4',
    grassColor: '#312e81',
    nightMode: true,
    weatherEffect: 'cyberGrid',
    ambientLight: 0.25,
    npcTypes: ['cyber', 'sports', 'semi'],
  },
  {
    id: 'paradise',
    nameFa: 'گلزار بهشتی و پردیس یونس آباد',
    nameEn: 'Younes Abad Paradise Garden',
    stageRange: [91, 100],
    roadColor: '#312e81',
    laneColor: '#fef08a',
    shoulderColor: '#831843',
    curbColor1: '#f472b6',
    curbColor2: '#fde047',
    grassColor: '#ec4899',
    nightMode: false,
    weatherEffect: 'petals',
    ambientLight: 1.0,
    npcTypes: ['limo', 'sports', 'cyber', 'semi'],
  },
];

export function getBiomeForStage(stage: number): BiomeConfig {
  const safeStage = Math.max(1, Math.min(100, stage));
  const biome = BIOMES.find(b => safeStage >= b.stageRange[0] && safeStage <= b.stageRange[1]);
  return biome || BIOMES[0];
}

export function getStageMilestones(stage: number): StageMilestoneInfo {
  const safeStage = Math.max(1, Math.min(100, stage));
  
  // Every 5 levels, max lives +1
  const bonusLives = Math.floor(safeStage / 5);
  const maxLives = 3 + bonusLives;
  
  // Level 10: Nitro unlocked
  const nitroUnlocked = safeStage >= 10;
  
  // Level 20: Gun unlocked
  const gunUnlocked = safeStage >= 20;
  
  // Nitro charges: 1 (lvl 10), 2 (lvl 40), 3 (lvl 60+)
  let nitroMaxCharges = 1;
  if (safeStage >= 60) nitroMaxCharges = 3;
  else if (safeStage >= 40) nitroMaxCharges = 2;
  
  // Gun ammo capacity: 3 (lvl 20), 5 (lvl 30), 7 (lvl 50+)
  let gunMaxAmmo = 3;
  if (safeStage >= 50) gunMaxAmmo = 7;
  else if (safeStage >= 30) gunMaxAmmo = 5;

  return {
    nitroUnlocked,
    gunUnlocked,
    maxLives,
    nitroMaxCharges,
    gunMaxAmmo,
  };
}

export const STORAGE_KEY = 'younes_abad_save_v1';

export const DEFAULT_SAVE_DATA: GameSaveData = {
  coins: 50,
  highestStage: 1,
  selectedCarId: 1,
  selectedCharacterId: 'maman_bozorg',
  unlockedCars: [1, 2],
  unlockedCharacters: ['maman_bozorg'],
  soundEnabled: true,
  musicEnabled: true,
  highScore: 0,
  overtakenCount: 0,
};

export function loadGameSave(): GameSaveData {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return DEFAULT_SAVE_DATA;
    const parsed = JSON.parse(raw);
    return {
      ...DEFAULT_SAVE_DATA,
      ...parsed,
    };
  } catch {
    return DEFAULT_SAVE_DATA;
  }
}

export function saveGameSave(data: GameSaveData): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
  } catch (err) {
    console.error('Failed to save game state:', err);
  }
}
