import { BiomeConfig, CarData, CharacterData, GameSaveData, StageMilestoneInfo } from '../types';

export const CHARACTERS: CharacterData[] = [
  {
    id: 'mamad',
    nameFa: 'ممد',
    nameEn: 'Mamad',
    avatarColor: '#3b82f6',
    role: 'رفیق فابریک غفلت و راننده جسور',
    description: 'کاراکتر آغازین و باوفا. مصمم برای رساندن خود به زندان قلعه‌نو و نجات غفلت. هندلینگ روان و تعادل عالی.',
    unlockedByDefault: true,
    price: 0,
    quoteFa: '«تا غفلت رو از قلعه‌نو نجات ندم، پامو از رو گاز برنمیدارم!»',
    perks: {
      speedMultiplier: 1.0,
      coinMultiplier: 1.0,
      handlingMultiplier: 1.0,
      extraLives: 0,
      hasDrift: false,
      hasRgbLights: false,
    },
  },
  {
    id: 'asghar_banafsheh',
    nameFa: 'اصغر بنفش',
    nameEn: 'Asghar Banafsheh',
    avatarColor: '#a855f7',
    role: 'سلطان بنفش و آهن‌ربای سکه',
    description: 'عاشق رنگ بنفش و تودوزی لوکس! ضریب دریافت سکه‌ها ۲ برابر (۲x) و دارای نورپردازی بنفش زیر ماشین.',
    unlockedByDefault: false,
    price: 250,
    quoteFa: '«رنگ بنفش نشانه اصالته، سکه‌ها خودشون جذب ماشینم میشن!»',
    perks: {
      speedMultiplier: 1.05,
      coinMultiplier: 2.0,
      handlingMultiplier: 1.1,
      extraLives: 0,
      hasDrift: false,
      hasRgbLights: true,
    },
  },
  {
    id: 'amin_shift',
    nameFa: 'امین شیفت',
    nameEn: 'Amin Shift',
    avatarColor: '#10b981',
    role: 'استاد تعویض دنده و کلاچ‌گیری',
    description: 'شتاب اولیه وحشتناک (+۲۰٪ شتاب و سرعت)، دست‌فرمان فوق‌العاده تیز برای لایی‌کشی بین موانع.',
    unlockedByDefault: false,
    price: 500,
    quoteFa: '«شیفت زدن من صدم ثانیه‌ست، هیچ ماشینی به گرد پایم نمیرسه!»',
    perks: {
      speedMultiplier: 1.15,
      coinMultiplier: 1.1,
      handlingMultiplier: 1.35,
      extraLives: 0,
      hasDrift: true,
      hasRgbLights: false,
    },
  },
  {
    id: 'dj',
    nameFa: 'DJ (دی‌جی)',
    nameEn: 'DJ',
    avatarColor: '#ec4899',
    role: 'هیولای بیس و چراغ‌های RGB نئونی',
    description: 'سیستم صوتی زلزله! چراغ‌های جلو و زیر خودرو نورپردازی رقصان هفت‌رنگ RGB دارند و ۱ جان اضافی دارد.',
    unlockedByDefault: false,
    price: 900,
    quoteFa: '«بیس سیستم ماشین من موانع اتوبان رو به لرزه درمیاره!»',
    perks: {
      speedMultiplier: 1.12,
      coinMultiplier: 1.3,
      handlingMultiplier: 1.15,
      extraLives: 1,
      hasDrift: false,
      hasRgbLights: true,
    },
  },
  {
    id: 'mamad_cj',
    nameFa: 'ممد سی جی',
    nameEn: 'Mamad CJ',
    avatarColor: '#eab308',
    role: 'افسانه سن آندریاس در اتوبان ایران',
    description: 'زره بدنه قوی، دریفت‌های حرفه‌ای و سرعت بالا (+۱۸٪) با قابلیت جمع‌آوری تیر و نیترو دو برابر.',
    unlockedByDefault: false,
    price: 1500,
    quoteFa: '«Ah shit, here we go again... غفلت داداش اومدم!»',
    perks: {
      speedMultiplier: 1.18,
      coinMultiplier: 1.35,
      handlingMultiplier: 1.25,
      extraLives: 1,
      hasDrift: true,
      hasRgbLights: false,
    },
  },
  {
    id: 'ferdinand',
    nameFa: 'فردیناند',
    nameEn: 'Ferdinand',
    avatarColor: '#0284c7',
    role: 'مهندسی دقیق و سرعت ویرانگر',
    description: 'سرعت نهایی فوق‌العاده بالا (+۲۵٪ سرعت) و مقاومت بالا در برابر تصادف و ۲ جان اضافه.',
    unlockedByDefault: false,
    price: 2400,
    quoteFa: '«مهندسی دقیق یعنی با سرعت ۲۰۰ تا بدون ترمز از پیچ‌ها رد شی!»',
    perks: {
      speedMultiplier: 1.25,
      coinMultiplier: 1.4,
      handlingMultiplier: 1.3,
      extraLives: 2,
      hasDrift: true,
      hasRgbLights: false,
    },
  },
  {
    id: 'farbod',
    nameFa: 'فربد',
    nameEn: 'Farbod',
    avatarColor: '#f97316',
    role: 'تک‌تیرانداز اتوبان و متخصص سلاح',
    description: 'مجهز به تیربار قدرتمند، ظرفیت مهمات بالا، شلیک‌های ویرانگر و تخریب آنی موانع و ۲ جان اضافی.',
    unlockedByDefault: false,
    price: 3500,
    quoteFa: '«مسیر رو با تیربار باز می‌کنم تا غفلت از قلعه‌نو خلاص بشه!»',
    perks: {
      speedMultiplier: 1.22,
      coinMultiplier: 1.5,
      handlingMultiplier: 1.2,
      extraLives: 2,
      hasDrift: false,
      hasRgbLights: true,
    },
  },
  {
    id: 'haj_ali',
    nameFa: 'حاج علی',
    nameEn: 'Haj Ali',
    avatarColor: '#ef4444',
    role: 'سلطان و پیشکسوت اتوبان‌های کشور',
    description: 'قدرتمندترین و شکست‌ناپذیرترین کاراکتر! ۳ جان اضافی، ضریب سکه ۲.۵ برابر، سرعت خارق‌العاده و هندلینگ بی‌نظیر.',
    unlockedByDefault: false,
    price: 6000,
    minLevelToUnlock: 30,
    quoteFa: '«من کل اتوبان‌های ایران رو چشم‌بسته رفتم، قلعه‌نو که جای خود دارد!»',
    perks: {
      speedMultiplier: 1.35,
      coinMultiplier: 2.5,
      handlingMultiplier: 1.4,
      extraLives: 3,
      hasDrift: true,
      hasRgbLights: true,
    },
  },
];

export const CARS: CarData[] = [
  {
    id: 1,
    nameFa: 'پیکان جوانان ۴۸',
    nameEn: 'Paykan Javanan 48',
    price: 0,
    bodyColor: '#e11d48',
    secondaryColor: '#ffffff',
    topSpeed: 140,
    acceleration: 60,
    handling: 65,
    armor: 50,
    type: 'classic',
    unlockedByDefault: true,
  },
  {
    id: 2,
    nameFa: 'پراید ۱۱۱ اسپرت',
    nameEn: 'Pride 111 Sport',
    price: 0,
    bodyColor: '#f3f4f6',
    secondaryColor: '#1f2937',
    topSpeed: 145,
    acceleration: 68,
    handling: 75,
    armor: 40,
    type: 'hatchback',
    unlockedByDefault: true,
  },
  {
    id: 3,
    nameFa: 'سمند LX سورن',
    nameEn: 'Samand LX',
    price: 150,
    bodyColor: '#3b82f6',
    secondaryColor: '#1d4ed8',
    topSpeed: 160,
    acceleration: 70,
    handling: 70,
    armor: 65,
    type: 'sedan',
    unlockedByDefault: false,
  },
  {
    id: 4,
    nameFa: 'پژو ۲۰۶ تیپ ۵',
    nameEn: 'Peugeot 206',
    price: 300,
    bodyColor: '#eab308',
    secondaryColor: '#000000',
    topSpeed: 168,
    acceleration: 78,
    handling: 82,
    armor: 55,
    type: 'hatchback',
    unlockedByDefault: false,
  },
  {
    id: 5,
    nameFa: 'پژو پارس ELX گرگ',
    nameEn: 'Pars ELX Wolf',
    price: 450,
    bodyColor: '#ffffff',
    secondaryColor: '#1e293b',
    topSpeed: 175,
    acceleration: 80,
    handling: 78,
    armor: 60,
    type: 'sedan',
    unlockedByDefault: false,
  },
  {
    id: 6,
    nameFa: 'نیسان آبی سالار',
    nameEn: 'Nissan Blue Pickup',
    price: 600,
    bodyColor: '#0284c7',
    secondaryColor: '#22c55e',
    topSpeed: 150,
    acceleration: 65,
    handling: 60,
    armor: 95,
    type: 'pickup',
    unlockedByDefault: false,
  },
  {
    id: 7,
    nameFa: 'تاکسی زرد تهران',
    nameEn: 'Tehran Yellow Taxi',
    price: 750,
    bodyColor: '#eab308',
    secondaryColor: '#1e293b',
    topSpeed: 165,
    acceleration: 75,
    handling: 80,
    armor: 60,
    type: 'taxi',
    unlockedByDefault: false,
  },
  {
    id: 8,
    nameFa: 'پلیس نامحسوس ۱۱۰',
    nameEn: 'Police Patrol 110',
    price: 950,
    bodyColor: '#0f172a',
    secondaryColor: '#ffffff',
    topSpeed: 185,
    acceleration: 85,
    handling: 85,
    armor: 75,
    type: 'police',
    unlockedByDefault: false,
  },
  {
    id: 9,
    nameFa: 'دنا پلاس توربو اتومات',
    nameEn: 'Dena Plus Turbo',
    price: 1200,
    bodyColor: '#475569',
    secondaryColor: '#dc2626',
    topSpeed: 182,
    acceleration: 84,
    handling: 80,
    armor: 70,
    type: 'sedan',
    unlockedByDefault: false,
  },
  {
    id: 10,
    nameFa: 'فولکس بیتل قورباغه‌ای',
    nameEn: 'Retro Beetle',
    price: 1500,
    bodyColor: '#f97316',
    secondaryColor: '#fef08a',
    topSpeed: 160,
    acceleration: 72,
    handling: 88,
    armor: 55,
    type: 'classic',
    unlockedByDefault: false,
  },
  {
    id: 11,
    nameFa: 'شورولت کامارو عضلانی',
    nameEn: 'Muscle Charger',
    price: 1800,
    bodyColor: '#000000',
    secondaryColor: '#facc15',
    topSpeed: 190,
    acceleration: 88,
    handling: 74,
    armor: 80,
    type: 'muscle',
    unlockedByDefault: false,
  },
  {
    id: 12,
    nameFa: 'تویوتا پرادو آفرود',
    nameEn: 'Prado 4x4 Offroad',
    price: 2200,
    bodyColor: '#15803d',
    secondaryColor: '#334155',
    topSpeed: 175,
    acceleration: 75,
    handling: 72,
    armor: 95,
    type: 'suv',
    unlockedByDefault: false,
  },
  {
    id: 13,
    nameFa: 'هیوندای جنسیس کوپه',
    nameEn: 'Genesis Coupe',
    price: 2600,
    bodyColor: '#9333ea',
    secondaryColor: '#f43f5e',
    topSpeed: 195,
    acceleration: 90,
    handling: 86,
    armor: 65,
    type: 'sports',
    unlockedByDefault: false,
  },
  {
    id: 14,
    nameFa: 'مرسدس بنز S500 شاهانه',
    nameEn: 'Mercedes Luxury VIP',
    price: 3000,
    bodyColor: '#1e293b',
    secondaryColor: '#94a3b8',
    topSpeed: 200,
    acceleration: 92,
    handling: 85,
    armor: 85,
    type: 'sedan',
    unlockedByDefault: false,
  },
  {
    id: 15,
    nameFa: 'پورشه ۹۱۱ توربو S',
    nameEn: 'Porsche 911 Turbo',
    price: 3500,
    bodyColor: '#e11d48',
    secondaryColor: '#0f172a',
    topSpeed: 210,
    acceleration: 95,
    handling: 92,
    armor: 70,
    type: 'sports',
    unlockedByDefault: false,
  },
  {
    id: 16,
    nameFa: 'لامبورگینی اونتادور خشمگین',
    nameEn: 'Aventador V12',
    price: 4200,
    bodyColor: '#06b6d4',
    secondaryColor: '#0891b2',
    topSpeed: 220,
    acceleration: 98,
    handling: 90,
    armor: 65,
    type: 'sports',
    unlockedByDefault: false,
  },
  {
    id: 17,
    nameFa: 'سایبر رودستر ۲۰۷۷',
    nameEn: 'Cyber Roadster 2077',
    price: 5000,
    bodyColor: '#0f172a',
    secondaryColor: '#22d3ee',
    topSpeed: 225,
    acceleration: 99,
    handling: 94,
    armor: 80,
    type: 'hyper',
    unlockedByDefault: false,
  },
  {
    id: 18,
    nameFa: 'فرمول یک ردبول توربو',
    nameEn: 'Formula One Redline',
    price: 6000,
    bodyColor: '#1e1b4b',
    secondaryColor: '#fbbf24',
    topSpeed: 235,
    acceleration: 100,
    handling: 98,
    armor: 50,
    type: 'hyper',
    unlockedByDefault: false,
  },
  {
    id: 19,
    nameFa: 'بوگاتی شیرون صاعقه',
    nameEn: 'Chiron Lightning',
    price: 7500,
    bodyColor: '#172554',
    secondaryColor: '#60a5fa',
    topSpeed: 245,
    acceleration: 100,
    handling: 95,
    armor: 85,
    type: 'hyper',
    unlockedByDefault: false,
  },
  {
    id: 20,
    nameFa: 'سلطان طلایی یونس آباد (ویژه)',
    nameEn: 'Younes Gold Sultan',
    price: 10000,
    bodyColor: '#eab308',
    secondaryColor: '#fef08a',
    topSpeed: 250,
    acceleration: 100,
    handling: 100,
    armor: 100,
    type: 'hyper',
    unlockedByDefault: false,
  },
  {
    id: 21,
    nameFa: 'موتور سنگین هوندا ۱۰۰۰ (سرعتی)',
    nameEn: 'Superbike 1000cc',
    price: 1800,
    bodyColor: '#dc2626',
    secondaryColor: '#1e293b',
    topSpeed: 215,
    acceleration: 98,
    handling: 96,
    armor: 30,
    type: 'sports',
    unlockedByDefault: false,
  },
  {
    id: 22,
    nameFa: 'تراکتور غول‌پیکر کشاورزی (قدرتی)',
    nameEn: 'Heavy Farm Tractor',
    price: 2200,
    bodyColor: '#15803d',
    secondaryColor: '#eab308',
    topSpeed: 140,
    acceleration: 60,
    handling: 55,
    armor: 100,
    type: 'suv',
    unlockedByDefault: false,
  },
  {
    id: 23,
    nameFa: 'تریلی ۱۸ چرخ جاده‌ای (سلطان بار)',
    nameEn: '18-Wheeler Freight Truck',
    price: 3200,
    bodyColor: '#b45309',
    secondaryColor: '#334155',
    topSpeed: 165,
    acceleration: 50,
    handling: 45,
    armor: 100,
    type: 'sedan',
    unlockedByDefault: false,
  },
  {
    id: 24,
    nameFa: 'وانت بار نیسان اسپرت (حامل بار)',
    nameEn: 'Sport Pickup Van',
    price: 1500,
    bodyColor: '#15803d',
    secondaryColor: '#fef08a',
    topSpeed: 175,
    acceleration: 85,
    handling: 80,
    armor: 70,
    type: 'pickup',
    unlockedByDefault: false,
  },
  {
    id: 25,
    nameFa: 'ماشین فرمول یک حرفه‌ای (سرعت مافوق)',
    nameEn: 'Pro Formula 1 Racer',
    price: 4500,
    bodyColor: '#dc2626',
    secondaryColor: '#ffffff',
    topSpeed: 245,
    acceleration: 100,
    handling: 98,
    armor: 50,
    type: 'f1',
    unlockedByDefault: false,
  },
  {
    id: 26,
    nameFa: 'موتور سنگین مسابقه‌ای (تک‌چرخ‌زن)',
    nameEn: 'Racing Superbike',
    price: 2000,
    bodyColor: '#2563eb',
    secondaryColor: '#93c5fd',
    topSpeed: 220,
    acceleration: 99,
    handling: 95,
    armor: 30,
    type: 'bike',
    unlockedByDefault: false,
  },
  {
    id: 27,
    nameFa: 'دوچرخه کورسی فوق‌سبک (استقامتی)',
    nameEn: 'Pro Racing Bicycle',
    price: 900,
    bodyColor: '#eab308',
    secondaryColor: '#1e293b',
    topSpeed: 130,
    acceleration: 75,
    handling: 92,
    armor: 15,
    type: 'bicycle',
    unlockedByDefault: false,
  },
  {
    id: 28,
    nameFa: 'جت موشکی جاده‌ای (صاعقه زمینی)',
    nameEn: 'Jet Rocket Car',
    price: 8500,
    bodyColor: '#475569',
    secondaryColor: '#38bdf8',
    topSpeed: 255,
    acceleration: 100,
    handling: 94,
    armor: 90,
    type: 'jet',
    unlockedByDefault: false,
  },
];


export const BIOMES: BiomeConfig[] = [
  {
    id: 'forest',
    nameFa: 'جنگل‌های سرسبز شمال',
    nameEn: 'Green Forest Highway',
    stageRange: [1, 10],
    roadColor: '#2b2d42',
    laneColor: '#edf2f4',
    shoulderColor: '#1e3a1e',
    curbColor1: '#ffffff',
    curbColor2: '#ef4444',
    grassColor: '#15803d',
    nightMode: false,
    weatherEffect: 'none',
    ambientLight: 1.0,
    npcTypes: ['paykan', 'pride', 'sedan', 'pickup', 'police'],
  },
  {
    id: 'desert',
    nameFa: 'کویر و تپه‌های شنی لوت',
    nameEn: 'Desert Sand Dunes',
    stageRange: [11, 20],
    roadColor: '#3f3730',
    laneColor: '#fef08a',
    shoulderColor: '#a16207',
    curbColor1: '#ffffff',
    curbColor2: '#f59e0b',
    grassColor: '#ca8a04',
    nightMode: false,
    weatherEffect: 'none',
    ambientLight: 1.0,
    npcTypes: ['truck', 'tractor', 'nissan_blue', 'semi', 'pickup'],
  },
  {
    id: 'rain',
    nameFa: 'اتوبان بارانی و آسفالت خیس',
    nameEn: 'Rainy Night Highway',
    stageRange: [21, 30],
    roadColor: '#111827',
    laneColor: '#93c5fd',
    shoulderColor: '#0f172a',
    curbColor1: '#60a5fa',
    curbColor2: '#1e40af',
    grassColor: '#064e3b',
    nightMode: true,
    weatherEffect: 'rain',
    ambientLight: 0.35,
    npcTypes: ['sedan', 'tanker', 'ambulance', 'truck', 'police'],
  },
  {
    id: 'snow',
    nameFa: 'جاده برفی و یخ‌زده البرز',
    nameEn: 'Snowy Alpine Pass',
    stageRange: [31, 40],
    roadColor: '#334155',
    laneColor: '#e2e8f0',
    shoulderColor: '#94a3b8',
    curbColor1: '#f8fafc',
    curbColor2: '#38bdf8',
    grassColor: '#f1f5f9',
    nightMode: false,
    weatherEffect: 'snow',
    ambientLight: 0.9,
    npcTypes: ['snowplow', 'truck', 'sedan', 'semi', 'police'],
  },
  {
    id: 'noir',
    nameFa: 'خیابان‌های نوآر سیاه و سفید',
    nameEn: 'Monochrome Noir City',
    stageRange: [41, 50],
    roadColor: '#18181b',
    laneColor: '#e4e4e7',
    shoulderColor: '#27272a',
    curbColor1: '#ffffff',
    curbColor2: '#52525b',
    grassColor: '#3f3f46',
    nightMode: true,
    weatherEffect: 'none',
    ambientLight: 0.4,
    npcTypes: ['limo', 'sedan', 'truck', 'paykan', 'police'],
  },
  {
    id: 'lava',
    nameFa: 'جاده آتشفشانی دماوند خروشان',
    nameEn: 'Volcanic Magma Gorge',
    stageRange: [51, 60],
    roadColor: '#1c1917',
    laneColor: '#f97316',
    shoulderColor: '#7c2d12',
    curbColor1: '#ea580c',
    curbColor2: '#451a03',
    grassColor: '#b91c1c',
    nightMode: true,
    weatherEffect: 'embers',
    ambientLight: 0.45,
    npcTypes: ['firetruck', 'truck', 'sports', 'semi', 'police'],
  },
  {
    id: 'mountain',
    nameFa: 'گردنه کوهستانی و صخره‌ای حیران',
    nameEn: 'Rocky Mountain Ridge',
    stageRange: [61, 70],
    roadColor: '#334155',
    laneColor: '#fbbf24',
    shoulderColor: '#475569',
    curbColor1: '#e2e8f0',
    curbColor2: '#dc2626',
    grassColor: '#475569',
    nightMode: false,
    weatherEffect: 'none',
    ambientLight: 0.95,
    npcTypes: ['bus', 'nissan_blue', 'truck', 'sedan', 'pickup'],
  },
  {
    id: 'ocean',
    nameFa: 'اتوبان ساحلی خلیج فارس',
    nameEn: 'Ocean Coastal Highway',
    stageRange: [71, 80],
    roadColor: '#1e293b',
    laneColor: '#fef08a',
    shoulderColor: '#0284c7',
    curbColor1: '#38bdf8',
    curbColor2: '#ffffff',
    grassColor: '#0369a1',
    nightMode: false,
    weatherEffect: 'none',
    ambientLight: 1.0,
    npcTypes: ['sedan', 'sports', 'bus', 'semi', 'police'],
  },
  {
    id: 'cyberpunk',
    nameFa: 'شهر نئونی سایبرپانک ۲۰۷۷',
    nameEn: 'Cyberpunk Neon City',
    stageRange: [81, 90],
    roadColor: '#090d16',
    laneColor: '#06b6d4',
    shoulderColor: '#1e1b4b',
    curbColor1: '#f43f5e',
    curbColor2: '#06b6d4',
    grassColor: '#312e81',
    nightMode: true,
    weatherEffect: 'cyberGrid',
    ambientLight: 0.25,
    npcTypes: ['cyber', 'sports', 'semi', 'police'],
  },
  {
    id: 'paradise',
    nameFa: 'گلزار بهشتی و پردیس یونس آباد',
    nameEn: 'Younes Abad Paradise Garden',
    stageRange: [91, 100],
    roadColor: '#312e81',
    laneColor: '#fef08a',
    shoulderColor: '#831843',
    curbColor1: '#f472b6',
    curbColor2: '#fde047',
    grassColor: '#ec4899',
    nightMode: false,
    weatherEffect: 'petals',
    ambientLight: 1.0,
    npcTypes: ['limo', 'sports', 'cyber', 'semi', 'police', 'pickup'],
  },
];

export interface StoryChapter {
  id: number;
  stageTrigger: number;
  titleFa: string;
  subtitleFa: string;
  speakerFa: string;
  avatarColor: string;
  messageFa: string;
  objectiveFa: string;
}

export const STORY_CHAPTERS: StoryChapter[] = [
  {
    id: 1,
    stageTrigger: 1,
    titleFa: 'فصل ۱: خبر ناگوار و آغاز ماجرا',
    subtitleFa: 'غفلت کجاست؟!',
    speakerFa: 'ممد',
    avatarColor: '#3b82f6',
    messageFa: 'بچه‌ها غفلت رو گرفتن! رئیس باند مافیای جاده، غفلت بهترین دوستمون رو دزدیده و برده به زندان فوق امنیتی «قلعه‌نو»! باید سریع گازشو بگیریم و نجاتش بدیم!',
    objectiveFa: 'گذر از اتوبان و جمع‌آوری سکه و نیترو برای شروع عملیات نجات غفلت',
  },
  {
    id: 2,
    stageTrigger: 10,
    titleFa: 'فصل ۲: کمین‌گاه کویر لوت',
    subtitleFa: 'نفوذ به قلمرو شن‌های داغ',
    speakerFa: 'اصغر بنفش',
    avatarColor: '#a855f7',
    messageFa: 'رسیدیم به کویر! نوچه‌های مافیا جاده رو با بشکه و مانع بستن. از تیربار و نیترو استفاده کنید تا موانع رو خرد کنیم!',
    objectiveFa: 'تیراندازی به موانع و ماشین‌های سد معبر',
  },
  {
    id: 3,
    stageTrigger: 25,
    titleFa: 'فصل ۳: گردنه‌های لغزنده بارانی',
    subtitleFa: 'پیچ‌های تند شمال',
    speakerFa: 'امین شیفت',
    avatarColor: '#10b981',
    messageFa: 'جاده بارونی و به شدت لغزنده‌ست! حواستون به پیچ‌های ناگهانی جاده و ماشین‌های شوتی باشه که یهو جلوتون نپیچن!',
    objectiveFa: 'کنترل دقیق در پیچ‌های جاده و سبقت بدون تصادف',
  },
  {
    id: 4,
    stageTrigger: 50,
    titleFa: 'فصل ۴: تاریکی شبانه طهران',
    subtitleFa: 'نیمه راه تا قلعه‌نو',
    speakerFa: 'DJ',
    avatarColor: '#ec4899',
    messageFa: 'چراغ‌های نئونی رو روشن کنید! به نیمه راه رسیدیم ولی گارد قلعه‌نو متوجه نزدیک شدن ما شده و جاده پر از موانع سنگی شده!',
    objectiveFa: 'روشن کردن نیترو و رد کردن خطرات شبانه',
  },
  {
    id: 5,
    stageTrigger: 75,
    titleFa: 'فصل ۵: خط ساحلی و درگیری سنگین',
    subtitleFa: 'نزدیک شدن به دژ اصلی',
    speakerFa: 'فربد',
    avatarColor: '#f97316',
    messageFa: 'تیربارها رو آماده شلیک کنید! کامیون‌ها و ماشین‌های زرهی مافیا سعی دارن نذارن به دروازه قلعه‌نو برسیم!',
    objectiveFa: 'تخریب خودروهای مهاجم با شلیک‌های پیاپی',
  },
  {
    id: 6,
    stageTrigger: 100,
    titleFa: 'فصل نهایی: نبرد در زندان قلعه‌نو',
    subtitleFa: 'آزادی بزرگ غفلت!',
    speakerFa: 'حاج علی',
    avatarColor: '#ef4444',
    messageFa: 'اینم از قلعه‌نو! دیوارهای زندان رو با نیترو درهم بکوبید و رفیقمون غفلت رو بعد از ۱۰۰ مرحله دلاوری آزاد کنید!',
    objectiveFa: 'فتح مرحله ۱۰۰ و نجات رسمی غفلت با افتخار!',
  },
];

export function getStoryChapterForStage(stage: number): StoryChapter | undefined {
  return STORY_CHAPTERS.find(ch => ch.stageTrigger === stage);
}

export function getBiomeForStage(stage: number): BiomeConfig {
  const safeStage = Math.max(1, Math.min(100, stage));
  const biome = BIOMES.find(b => safeStage >= b.stageRange[0] && safeStage <= b.stageRange[1]);
  return biome || BIOMES[0];
}

export function getStageMilestones(stage: number): StageMilestoneInfo {
  const safeStage = Math.max(1, Math.min(100, stage));
  
  // Max lives formula: starts at 3, +1 every 5 stages
  const bonusLives = Math.floor(safeStage / 5);
  const maxLives = 3 + bonusLives;
  
  // Nitro unlocked immediately from Stage 1 for maximum fun!
  const nitroUnlocked = true;
  
  // Gun unlocked from Stage 1 so shooting is always available with ammo
  const gunUnlocked = true;
  
  // Nitro charges: 2 (base), 3 (lvl 20+), 4 (lvl 50+)
  let nitroMaxCharges = 2;
  if (safeStage >= 50) nitroMaxCharges = 4;
  else if (safeStage >= 20) nitroMaxCharges = 3;
  
  // Gun ammo capacity: 5 (lvl 1), 8 (lvl 20), 12 (lvl 45+)
  let gunMaxAmmo = 5;
  if (safeStage >= 45) gunMaxAmmo = 12;
  else if (safeStage >= 20) gunMaxAmmo = 8;

  return {
    nitroUnlocked,
    gunUnlocked,
    maxLives,
    nitroMaxCharges,
    gunMaxAmmo,
  };
}

export const STORAGE_KEY = 'nejat_ghaflat_save_v2';

export const DEFAULT_SAVE_DATA: GameSaveData = {
  coins: 80,
  highestStage: 1,
  selectedCarId: 1,
  selectedCharacterId: 'mamad',
  unlockedCars: [1, 2],
  unlockedCharacters: ['mamad'],
  soundEnabled: true,
  musicEnabled: true,
  highScore: 0,
  overtakenCount: 0,
  unlockedCustomizations: ['decal:none', 'tint:0', 'underglow:none', 'spoiler:none', 'rim:stock'],
  aparatRewardClaimed: false,
};

export function loadGameSave(): GameSaveData {
  try {
    const raw = localStorage.getItem(STORAGE_KEY) || localStorage.getItem('younes_abad_save_v1');
    if (!raw) return DEFAULT_SAVE_DATA;
    const parsed = JSON.parse(raw);
    
    // Migrate old character IDs if necessary
    const validCharIds = ['mamad', 'asghar_banafsheh', 'amin_shift', 'dj', 'mamad_cj', 'ferdinand', 'farbod', 'haj_ali'];
    let selChar = parsed.selectedCharacterId;
    if (!validCharIds.includes(selChar)) {
      selChar = 'mamad';
    }

    const unlChars = Array.isArray(parsed.unlockedCharacters)
      ? parsed.unlockedCharacters.filter((c: string) => validCharIds.includes(c))
      : ['mamad'];
    if (unlChars.length === 0) unlChars.push('mamad');

    return {
      ...DEFAULT_SAVE_DATA,
      ...parsed,
      selectedCharacterId: selChar,
      unlockedCharacters: unlChars,
    };
  } catch {
    return DEFAULT_SAVE_DATA;
  }
}

export function saveGameSave(data: GameSaveData): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
  } catch (err) {
    console.error('Failed to save game state:', err);
  }
}
